### ISSUE TITLE
Base62 is not thread safe

### ISSUE THREAD

**Issue by kosprov** [akhawaja/ksuid#3]
Hi,

Your implementation of `Base62` uses a static variable for the `StringBuilder` that collects output characters. This makes it non-thread-safe and cannot be used in a server environment.

**Comment by akhawaja** [comment]
Hi @kosprov. I take your point and will revisit the Base62 class as time permits. Cheers!

**Comment by akhawaja** [comment]
Hi @kosprov. Going forward, I intend to remove the Base62 class included in this library in favor of one that is available on Maven Central. I am closing this issue. Thank you for examining the repository and offering your feedback.
